version = 1
SPDX-PackageName = "ocm-spec"
SPDX-PackageSupplier = "ospo@sap.com"
SPDX-PackageDownloadLocation = "https://github.com/open-component-model/ocm-spec"
SPDX-PackageComment = "This specification is licensed under the Community Specification License 1.0."

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "SAP SE or an SAP affiliate company and Open Component Model contributors"
SPDX-License-Identifier = "Community-Spec-1.0"

